var translateOptions = {
  lng: "en",
  debug: false,
  resources: {
    en: {
      translation: {
        "thunderstorm with light rain": "yüngül yağışla müşayiət olunan tufan",
        "thunderstorm with rain": "yağışlı tufan",
        "thunderstorm with heavy rain": "şiddətli yağışla birlikdə tufan",
        "light thunderstorm": "yüngül tufan",
        thunderstorm: "tufan",
        "heavy thunderstorm": "güclü tufan",
        "ragged thunderstorm": "güclü tufan",
        "thunderstorm with light drizzle": "yüngül çiskinli tufan",
        "thunderstorm with drizzle": "çiskinli tufan",
        "thunderstorm with heavy drizzle": "güclü çiskinli tufan",
        "light intensity drizzle": "yüngül çiskin",
        drizzle: "çiskin",
        "heavy intensity drizzle": "şiddətli çiskin",
        "light intensity drizzle rain": "yüngül intensivlikli çiskinli yağış",
        "drizzle rain": "çiskinli yağış",
        "heavy intensity drizzle rain": "şiddətli çiskinli yağış",
        "shower rain and drizzle": "leysan yağış və çiskin",
        "heavy shower rain and drizzle": "leysan yağış və çiskin",
        "shower drizzle": "çiskinli yağış",
        "light rain": "yüngül yağış",
        "moderate rain": "mülayim yağış",
        "heavy intensity rain": "şiddətli yağış",
        "very heavy rain": "çox güclü yağış",
        "extreme rain": "həddindən artıq yağış",
        "freezing rain": "dondurucu yağış",
        "light intensity shower rain": "yüngül intensivlikli leysan yağışı",
        "shower rain": "leysan yağışı",
        "heavy intensity shower rain": "şiddətli leysan yağışı",
        "ragged shower rain": "şiddətli leysan yağışı",
        "light snow": "yüngül qar",
        snow: "qar",
        "heavy snow": "güclü qar",
        sleet: "sulu qar",
        "light shower sleet": "yüngül sulu qar",
        "shower sleet": "güclü sulu qar",
        "light rain and snow": "az yağış və qar",
        "rain and snow": "yağış və qar",
        "light shower snow": "yüngül leysan qar",
        "shower snow": "leysan qar",
        "heavy shower snow": "güclü leysan qar",
        mist: "duman",
        smoke: "tüstü",
        haze: "duman",
        "sand/dust whirls": "qum/toz burulğanları",
        fog: "duman",
        sand: "qum",
        dust: "toz",
        "volcanic ash": "vulkanik kül",
        squalls: "qasırğa",
        tornado: "tornado",
        "clear sky": "təmiz səma",
        "few clouds": "az buludlu",
        "scattered clouds": "parçalı buludlar",
        "broken clouds": "parçalı buludlar",
        "overcast clouds": "buludlu",
      },
    },
  },
};

export { translateOptions };
